# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d14fcbcd27ee101e3978cf0e086134d24da3e58a190d4607183ea638aa112a3acbc789fd415afc438d53a2e4b84d3c9f945bb6a59deadbc8426be5288c056e

test:
  secret_key_base: aa16eefd30483f3c81826b6a305277c068df7f2864547d8de9f6ae202e7b9f44b8d6c9b92012d4ee967f8820d12cef8432188a4e2141689567969d2a441d6f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
